DROP DATABASE IF EXISTS umwconnections;
CREATE DATABASE IF NOT EXISTS umwconnections;
USE umwconnections;

CREATE TABLE IF NOT EXISTS Users (
	email varchar(100) NOT NULL,
  	lastname varchar(25) NOT NULL,
  	firstname varchar(25) NOT NULL,
  	gender ENUM('Male', 'Female') NOT NULL,
  	phone varchar(10) NOT NULL,
  	interests blob NOT NULL,
  	description blob,
  	lookingFor ENUM('Date', 'Relationship', 'Friendship', 'Study Group', 'Sports') NOT NULL,
  	major varchar(50),
  	PRIMARY KEY (email)
);

CREATE TABLE IF NOT EXISTS Login (
	email varchar(100) NOT NULL,
	pw varchar(20) NOT NULL,
	PRIMARY KEY (email)
);

INSERT INTO Users (email,lastname,firstname,gender,phone,interests,description,lookingFor,major) VALUES 
('semper@eu.ca','Gray','Todd','Male','4537638355','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing','Date','egestas.'),
('amet.faucibus.ut@hendrerit.com','Horn','Russell','Male','3152505279','Lorem','Lorem','Date','metus vitae velit'),
('lorem.ut.aliquam@vulputateposuerevulputate.ca','Fisher','Yen','Female','8414639889','Lorem ipsum dolor','Lorem ipsum','Relationship','nisl. Nulla'),
('et.rutrum.non@gravidasit.com','Hahn','Germane','Female','2635477840','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet,','Relationship','a,'),
('tincidunt@orciluctuset.ca','Herrera','Dieter','Female','8662835372','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur','Study Group','orci. Ut semper'),
('facilisis@molestiedapibusligula.com','Tate','Colby','Female','7631496679','Lorem','Lorem ipsum','Relationship','iaculis nec,'),
('in@aliquetPhasellus.org','Sexton','Maite','Female','2523286236','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Study Group','metus vitae'),
('sit.amet.ultricies@auctor.org','Mann','Sybil','Male','3713865184','Lorem ipsum dolor sit amet,','Lorem ipsum','Date','pede. Suspendisse dui.'),
('dictum.eleifend@ipsumleo.com','Compton','Dalton','Male','9754025312','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet,','Sports','mauris elit,'),
('ligula.Aliquam.erat@Vestibulum.ca','Jarvis','Indira','Male','7614598990','Lorem ipsum dolor','Lorem ipsum dolor sit amet,','Sports','cursus vestibulum.'),
('ac@Nulla.org','Hutchinson','Declan','Male','3702463813','Lorem ipsum dolor sit','Lorem ipsum dolor','Date','feugiat tellus'),
('lectus.pede@felisadipiscing.com','Browning','Alan','Male','8484753990','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Date','consequat'),
('Fusce.aliquet@adipiscingligula.com','Sweet','Noel','Female','3838685961','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Relationship','lacinia vitae,'),
('ultrices@augueid.org','Mcclure','Prescott','Female','1674858616','Lorem ipsum','Lorem ipsum dolor','Sports','diam at pretium'),
('cursus.et@blanditcongueIn.org','Craig','Deanna','Male','9859827212','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Relationship','purus gravida'),
('sem.semper.erat@Donec.com','Odonnell','Jasmine','Female','3622617599','Lorem ipsum','Lorem ipsum dolor sit','Sports','Aliquam'),
('Proin.eget.odio@metus.ca','Collier','Xantha','Female','5695968129','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Friendship','felis. Donec tempor,'),
('a.mi.fringilla@nonmassa.org','Nielsen','Tara','Female','6032500096','Lorem ipsum dolor sit amet,','Lorem ipsum','Date','tempor erat neque'),
('a.tortor.Nunc@dictumeleifend.com','Graves','Zachery','Female','8693306456','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Sports','viverra. Donec'),
('In.mi.pede@congueturpis.edu','Cantrell','Dylan','Male','6656525755','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Relationship','egestas, urna justo'),
('ultrices@Aliquamtinciduntnunc.org','Barron','Hamish','Female','2577033685','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed','Friendship','non'),
('rutrum.non.hendrerit@odio.ca','Castro','Xaviera','Male','9014261975','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing','Study Group','risus. Donec'),
('Nullam@quis.edu','Ortega','Tallulah','Female','5013914330','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer','Relationship','tincidunt, nunc'),
('nec.luctus@rutrumeu.org','Owens','MacKensie','Female','7309801103','Lorem ipsum dolor','Lorem ipsum dolor sit amet,','Relationship','Donec vitae erat'),
('pede.Nunc.sed@magna.com','Riggs','Alvin','Male','3754484474','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Date','cursus'),
('non.magna.Nam@massa.com','French','Mufutau','Female','7407773121','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Sports','Phasellus'),
('amet.metus@nunc.org','Sims','Cathleen','Male','2462202980','Lorem ipsum','Lorem','Relationship','dui. Fusce aliquam,'),
('Sed@dapibusligulaAliquam.org','Mckay','Marvin','Female','2461617838','Lorem','Lorem ipsum dolor sit amet, consectetuer','Date','eget,'),
('eros.non.enim@augueidante.ca','Cooley','Theodore','Female','7573628790','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Sports','quis'),
('sagittis.augue.eu@famesac.org','Castaneda','Angelica','Male','9261018270','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur','Study Group','nec ante.'),
('felis@Nulla.edu','Atkins','Driscoll','Female','6433359350','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Friendship','convallis'),
('sapien@acipsumPhasellus.ca','Frank','Haley','Male','5387920256','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Sports','Pellentesque habitant'),
('pede.Cras@sapien.edu','Peterson','Sybill','Female','6161609401','Lorem ipsum dolor','Lorem ipsum dolor sit amet,','Study Group','Curabitur massa. Vestibulum'),
('amet.luctus@Donectempus.com','Combs','Ria','Female','3535051222','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Friendship','interdum libero'),
('sit.amet.consectetuer@semperpretiumneque.org','Nash','Azalia','Female','2206559064','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Study Group','nisi'),
('Vivamus@dictum.edu','Craft','Adena','Male','8691721377','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Relationship','arcu eu'),
('scelerisque.neque.Nullam@fringillaornare.org','Alvarez','Steel','Male','2091850932','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Relationship','iaculis odio. Nam'),
('eu.turpis@leoVivamusnibh.com','Burns','Leo','Female','7686795881','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Relationship','eu arcu. Morbi'),
('Aliquam@orci.org','Madden','Wylie','Male','9029888568','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Date','non, luctus'),
('pede.blandit.congue@per.ca','Gould','Imani','Female','1907819808','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Relationship','gravida nunc sed'),
('arcu.Sed@cursusIntegermollis.com','Mccoy','Fulton','Male','5616716408','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Date','mi,'),
('ante.dictum.cursus@dolorsitamet.ca','Ellis','Sharon','Male','7425997468','Lorem','Lorem ipsum dolor','Date','interdum. Sed auctor'),
('sit@senectuset.com','Nunez','Rhiannon','Female','5014856345','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Study Group','Cras'),
('laoreet.ipsum.Curabitur@NuncmaurisMorbi.edu','Hicks','Rama','Female','7499991377','Lorem ipsum dolor sit amet,','Lorem ipsum dolor','Sports','Morbi'),
('cursus.luctus.ipsum@eteuismod.ca','Faulkner','Nina','Female','3104843842','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Sports','auctor'),
('vitae.velit.egestas@acarcu.org','Rutledge','Melanie','Male','8921240625','Lorem ipsum dolor sit amet,','Lorem ipsum','Sports','Fusce aliquam, enim'),
('luctus.Curabitur@sedorci.org','Giles','Nigel','Male','1546249363','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer','Relationship','lacinia. Sed'),
('sollicitudin.a.malesuada@pellentesqueeget.org','York','Shaeleigh','Male','5134288812','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Sports','pretium neque. Morbi'),
('erat.in@Phasellusin.org','Hansen','Mari','Male','9676190519','Lorem ipsum','Lorem','Relationship','sit amet, risus.'),
('a.tortor.Nunc@orciconsectetuer.edu','Fuentes','Arthur','Female','1499457176','Lorem','Lorem ipsum dolor sit amet,','Relationship','ac metus'),
('scelerisque.sed.sapien@nonummyFuscefermentum.edu','Guzman','Malik','Male','5988927973','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Friendship','ante'),
('non@lacusvarius.ca','Medina','Laura','Female','6974462264','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Study Group','Fusce diam'),
('rhoncus@faucibusorciluctus.ca','Boone','Rhea','Male','9439026473','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Friendship','non ante'),
('arcu@diam.edu','Rocha','Chester','Female','6214256269','Lorem ipsum dolor sit amet,','Lorem ipsum','Relationship','turpis. In condimentum.'),
('Suspendisse.aliquet.sem@ornare.com','Foley','Hamish','Male','4188719135','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur','Sports','sit amet, consectetuer'),
('Curabitur@variusultricesmauris.org','Workman','Amber','Male','4321749520','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer','Relationship','est tempor bibendum.'),
('eget.massa@interdum.org','Baxter','Emily','Female','6235777851','Lorem ipsum dolor sit','Lorem ipsum','Relationship','nibh dolor,'),
('sit@faucibusorciluctus.com','Gamble','Steel','Male','8902535002','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Relationship','dui. Fusce'),
('mattis@sapien.edu','Wright','Amity','Male','3362262315','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit','Friendship','ante'),
('non.magna.Nam@estMauriseu.ca','Leonard','Karen','Male','6594831957','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Relationship','placerat,'),
('mi@infaucibus.edu','Whitney','Wing','Male','7406155539','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet,','Sports','Class'),
('quam.Curabitur@arcuvel.org','Mejia','Blaine','Male','7083833448','Lorem','Lorem','Study Group','scelerisque'),
('Nam.porttitor.scelerisque@euismod.ca','Wiggins','Hayfa','Male','6065774057','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Relationship','nunc. Quisque ornare'),
('Mauris.ut.quam@Utnecurna.ca','Hancock','Erica','Male','3238934412','Lorem ipsum dolor sit amet,','Lorem ipsum','Date','ante ipsum'),
('convallis@risusNulla.ca','Tucker','Alexis','Male','9438652446','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Relationship','lectus pede,'),
('lorem.auctor@lectuspedeultrices.com','West','Walter','Male','9859792658','Lorem ipsum dolor sit amet,','Lorem','Relationship','orci.'),
('vulputate@risusMorbi.com','Walton','Edward','Male','4279154134','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Relationship','adipiscing'),
('Aenean.egestas.hendrerit@lacus.org','Valenzuela','Hu','Male','4312748764','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Relationship','vulputate'),
('elit.fermentum.risus@anuncIn.org','Franks','Shay','Female','8787119293','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Relationship','mattis. Integer'),
('lectus@tincidunt.edu','Velazquez','Idona','Male','5778556368','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus.','Relationship','eu turpis. Nulla'),
('semper@justonecante.edu','Fernandez','Amir','Male','4913480346','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Friendship','ut, nulla.'),
('justo@Nunc.edu','Duffy','Kristen','Male','4802202541','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Date','montes, nascetur ridiculus'),
('in.consequat.enim@fringillaestMauris.org','Powers','Lamar','Female','8878268388','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer','Relationship','non, vestibulum'),
('feugiat.Lorem.ipsum@Donecfeugiatmetus.ca','Carver','Velma','Female','7689477293','Lorem','Lorem ipsum dolor sit amet,','Friendship','eu dui. Cum'),
('sapien.Aenean@Vivamusmolestiedapibus.ca','Wolfe','Baxter','Female','9293061018','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer','Study Group','non, vestibulum'),
('amet.ultricies.sem@velnislQuisque.edu','Shaffer','Kathleen','Female','7558478684','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Relationship','adipiscing non, luctus'),
('pharetra.sed@Sedauctorodio.ca','Leon','Camden','Female','6981745583','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit.','Study Group','ridiculus mus. Proin'),
('sit.amet@ut.ca','Carver','Nayda','Female','9234832816','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Sports','suscipit nonummy. Fusce'),
('auctor.non.feugiat@leo.org','Herrera','Lionel','Male','2724748121','Lorem ipsum','Lorem ipsum','Sports','quam, elementum'),
('per.inceptos@orciUtsemper.edu','Dickson','Russell','Male','9215497861','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Relationship','id,'),
('metus@ipsumleo.com','Quinn','Aurora','Male','9375206745','Lorem ipsum dolor','Lorem ipsum dolor sit amet,','Relationship','vel sapien imperdiet'),
('nunc.id@pellentesquetellus.edu','Evans','Dolan','Female','5025952382','Lorem','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur','Friendship','risus odio,'),
('orci.Ut.semper@doloregestasrhoncus.com','Navarro','Pearl','Female','7048540036','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Relationship','magna a'),
('enim.sit@odiotristiquepharetra.com','Hewitt','Barclay','Male','7729423287','Lorem ipsum','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Study Group','dolor dolor, tempus'),
('dolor.Donec@Aenean.com','George','Grady','Male','6791563406','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer','Study Group','Donec nibh enim,'),
('porttitor.eros@adipiscing.ca','Hess','Daquan','Male','9587166222','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Date','semper,'),
('metus@elit.com','Maynard','Steel','Male','5289148955','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing','Study Group','eu erat semper'),
('dictum.ultricies.ligula@ipsum.org','Workman','Patricia','Female','4309738752','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing','Sports','mollis vitae, posuere'),
('et.netus@Mauris.edu','Mcbride','Odessa','Male','2724154037','Lorem ipsum dolor sit amet,','Lorem ipsum dolor','Relationship','arcu.'),
('eu.accumsan.sed@laoreetposuere.org','Miller','Allistair','Female','7682754160','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Date','et, lacinia vitae,'),
('id.enim@egetmetus.org','Holden','Mary','Male','1262930116','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet,','Relationship','amet,'),
('a.feugiat@anteMaecenasmi.edu','Mayo','Evangeline','Female','3798725918','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet,','Sports','nunc est,'),
('quis.lectus.Nullam@ac.edu','Calderon','Honorato','Female','3946215197','Lorem ipsum dolor sit','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam','Sports','Integer vitae'),
('risus.quis.diam@inconsectetueripsum.edu','Fields','Clinton','Male','5336630251','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Study Group','vulputate dui, nec'),
('In.ornare.sagittis@malesuada.com','Harmon','Kim','Female','6846379842','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor.','Study Group','at'),
('Praesent@eteuismodet.com','Gilmore','Alec','Female','6478052589','Lorem ipsum dolor','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Sports','dictum magna. Ut'),
('interdum@consequatdolorvitae.edu','Espinoza','Yardley','Male','6397944740','Lorem','Lorem','Relationship','dis'),
('Morbi.neque@tristique.edu','Alvarez','Paula','Female','1021650354','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet,','Date','dictum eleifend,'),
('ante.ipsum@utipsumac.edu','Pittman','Tasha','Female','9902004060','Lorem','Lorem','Date','Quisque porttitor eros'),
('suscipit.est@Aliquamfringilla.edu','Griffith','Lisandra','Male','6388278478','Lorem ipsum dolor sit amet,','Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer','Sports','Sed diam');